github: [phoenixgoldz]
patreon: 
open_collective: 
ko_fi: phoenixgoldzstudios
buy_me_a_coffee: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
lfx_crowdfunding: 
polar: 
thanks_dev: 
custom: []
